# Generated by Django 2.1 on 2023-05-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230528_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(max_length=150),
        ),
    ]
