# Generated by Django 2.1 on 2023-05-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230529_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
